const songLists = [
  {
    id: 1,
    name: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    uri: 'spotify:track:0VjIjW4GlUZAMYd2vXMi3b',
  },
  {
    id: 2,
    name: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    uri: 'spotify:track:39LLxExYz6ewLAcYrzQQyP',
  },
  {
    id: 3,
    name: 'Watermelon Sugar',
    artist: 'Harry Styles',
    album: 'Fine Line',
    uri: 'spotify:track:6UelLqGlWMcVH1E5c4H7lY',
  },
  {
    id: 4,
    name: 'Save Your Tears',
    artist: 'The Weeknd',
    album: 'After Hours',
    uri: 'spotify:track:5QO79kh1waicV47BqGRL3g',
  },
  {
    id: 5,
    name: 'Peaches',
    artist: 'Justin Bieber',
    album: 'Justice',
    uri: 'spotify:track:4iJyoBOLtHqaGxP12qzhQI',
  },
  {
    id: 6,
    name: 'Good 4 U',
    artist: 'Olivia Rodrigo',
    album: 'SOUR',
    uri: 'spotify:track:09bwwB0fpgLQbWQmQ5Q5sm',
  },
  {
    id: 7,
    name: 'Stay',
    artist: 'The Kid LAROI',
    album: 'F*CK LOVE 3',
    uri: 'spotify:track:5HCyWlXZPP0y6Gqq8TgA20',
  },
  {
    id: 8,
    name: 'Bad Habits',
    artist: 'Ed Sheeran',
    album: '=',
    uri: 'spotify:track:3rmo8F54jFF8OgYsqTxm5d',
  },
  {
    id: 9,
    name: 'Montero (Call Me By Your Name)',
    artist: 'Lil Nas X',
    album: 'Montero',
    uri: 'spotify:track:1SC5rEoYDGUK4NfG82494W',
  },
  {
    id: 10,
    name: 'Kiss Me More',
    artist: 'Doja Cat',
    album: 'Planet Her',
    uri: 'spotify:track:3DarAbFujv6eYNliUTyqtz',
  },
  {
    id: 11,
    name: 'Industry Baby',
    artist: 'Lil Nas X',
    album: 'Montero',
    uri: 'spotify:track:27NovPIUIRrOZoCHxABJwK',
  },
  {
    id: 12,
    name: 'Shivers',
    artist: 'Ed Sheeran',
    album: '=',
    uri: 'spotify:track:50nfwKoDiSYg8zOCREWAm5',
  },
  {
    id: 13,
    name: 'Easy On Me',
    artist: 'Adele',
    album: '30',
    uri: 'spotify:track:46IZ0fSY2mpAiktS3KOqds',
  },
  {
    id: 14,
    name: 'Heat Waves',
    artist: 'Glass Animals',
    album: 'Dreamland',
    uri: 'spotify:track:3USxtqRwSYz57Ewm6wWRMp',
  },
  {
    id: 15,
    name: 'As It Was',
    artist: 'Harry Styles',
    album: "Harry's House",
    uri: 'spotify:track:4Dvkj6JhhA12EX05fT7y2e',
  },
];

export default songLists;
